// Code generated by protoc-gen-go.
// source: eventium.proto
// DO NOT EDIT!

/*
Package eventium is a generated protocol buffer package.

It is generated from these files:
	eventium.proto

It has these top-level messages:
	GetEventByIDRequest
	PostEventRequest
	PostEventResponse
	Location
	Eventum
*/
package eventium

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// =============================== MESSAGES
type GetEventByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetEventByIDRequest) Reset()                    { *m = GetEventByIDRequest{} }
func (m *GetEventByIDRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEventByIDRequest) ProtoMessage()               {}
func (*GetEventByIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetEventByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PostEventRequest struct {
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Event     *Eventum                   `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
}

func (m *PostEventRequest) Reset()                    { *m = PostEventRequest{} }
func (m *PostEventRequest) String() string            { return proto.CompactTextString(m) }
func (*PostEventRequest) ProtoMessage()               {}
func (*PostEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PostEventRequest) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *PostEventRequest) GetEvent() *Eventum {
	if m != nil {
		return m.Event
	}
	return nil
}

type PostEventResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	EventID bool `protobuf:"varint,2,opt,name=eventID" json:"eventID,omitempty"`
}

func (m *PostEventResponse) Reset()                    { *m = PostEventResponse{} }
func (m *PostEventResponse) String() string            { return proto.CompactTextString(m) }
func (*PostEventResponse) ProtoMessage()               {}
func (*PostEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PostEventResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PostEventResponse) GetEventID() bool {
	if m != nil {
		return m.EventID
	}
	return false
}

// =============================== OBJECTS
type Location struct {
	X float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Location) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Location) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Eventum struct {
	Location  *Location                  `protobuf:"bytes,16,opt,name=location" json:"location,omitempty"`
	Begin     *google_protobuf.Timestamp `protobuf:"bytes,17,opt,name=begin" json:"begin,omitempty"`
	End       *google_protobuf.Timestamp `protobuf:"bytes,18,opt,name=end" json:"end,omitempty"`
	Headline  string                     `protobuf:"bytes,19,opt,name=headline" json:"headline,omitempty"`
	MediaData []byte                     `protobuf:"bytes,20,opt,name=mediaData,proto3" json:"mediaData,omitempty"`
	Tags      []string                   `protobuf:"bytes,21,rep,name=tags" json:"tags,omitempty"`
}

func (m *Eventum) Reset()                    { *m = Eventum{} }
func (m *Eventum) String() string            { return proto.CompactTextString(m) }
func (*Eventum) ProtoMessage()               {}
func (*Eventum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Eventum) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Eventum) GetBegin() *google_protobuf.Timestamp {
	if m != nil {
		return m.Begin
	}
	return nil
}

func (m *Eventum) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Eventum) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *Eventum) GetMediaData() []byte {
	if m != nil {
		return m.MediaData
	}
	return nil
}

func (m *Eventum) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*GetEventByIDRequest)(nil), "eventium.GetEventByIDRequest")
	proto.RegisterType((*PostEventRequest)(nil), "eventium.PostEventRequest")
	proto.RegisterType((*PostEventResponse)(nil), "eventium.PostEventResponse")
	proto.RegisterType((*Location)(nil), "eventium.Location")
	proto.RegisterType((*Eventum)(nil), "eventium.Eventum")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Eventium service

type EventiumClient interface {
	PostEvent(ctx context.Context, in *PostEventRequest, opts ...grpc.CallOption) (*PostEventResponse, error)
	GetEventByID(ctx context.Context, in *GetEventByIDRequest, opts ...grpc.CallOption) (*Eventum, error)
}

type eventiumClient struct {
	cc *grpc.ClientConn
}

func NewEventiumClient(cc *grpc.ClientConn) EventiumClient {
	return &eventiumClient{cc}
}

func (c *eventiumClient) PostEvent(ctx context.Context, in *PostEventRequest, opts ...grpc.CallOption) (*PostEventResponse, error) {
	out := new(PostEventResponse)
	err := grpc.Invoke(ctx, "/eventium.Eventium/PostEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventiumClient) GetEventByID(ctx context.Context, in *GetEventByIDRequest, opts ...grpc.CallOption) (*Eventum, error) {
	out := new(Eventum)
	err := grpc.Invoke(ctx, "/eventium.Eventium/GetEventByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Eventium service

type EventiumServer interface {
	PostEvent(context.Context, *PostEventRequest) (*PostEventResponse, error)
	GetEventByID(context.Context, *GetEventByIDRequest) (*Eventum, error)
}

func RegisterEventiumServer(s *grpc.Server, srv EventiumServer) {
	s.RegisterService(&_Eventium_serviceDesc, srv)
}

func _Eventium_PostEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventiumServer).PostEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventium.Eventium/PostEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventiumServer).PostEvent(ctx, req.(*PostEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eventium_GetEventByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventiumServer).GetEventByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventium.Eventium/GetEventByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventiumServer).GetEventByID(ctx, req.(*GetEventByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Eventium_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventium.Eventium",
	HandlerType: (*EventiumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostEvent",
			Handler:    _Eventium_PostEvent_Handler,
		},
		{
			MethodName: "GetEventByID",
			Handler:    _Eventium_GetEventByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventium.proto",
}

func init() { proto.RegisterFile("eventium.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x4e, 0xea, 0x40,
	0x10, 0x86, 0xd9, 0x72, 0x38, 0xb4, 0x73, 0x08, 0x81, 0xe1, 0x98, 0x6c, 0xaa, 0x46, 0xd2, 0x44,
	0xe5, 0xc2, 0x14, 0x83, 0x37, 0x5e, 0x13, 0x90, 0x90, 0x78, 0x61, 0x36, 0xbe, 0x40, 0xa1, 0x6b,
	0xdd, 0x84, 0x76, 0xd1, 0xdd, 0x1a, 0x78, 0x11, 0x5f, 0xd1, 0xd7, 0x30, 0xdd, 0xd2, 0x96, 0x28,
	0x09, 0x77, 0x3b, 0x3b, 0xdf, 0xcc, 0xff, 0xcf, 0xce, 0x42, 0x9b, 0x7f, 0xf0, 0x44, 0x8b, 0x34,
	0xf6, 0xd7, 0xef, 0x52, 0x4b, 0xb4, 0x8b, 0xd8, 0xbd, 0x88, 0xa4, 0x8c, 0x56, 0x7c, 0x68, 0xee,
	0x17, 0xe9, 0xcb, 0x50, 0x8b, 0x98, 0x2b, 0x1d, 0xc4, 0xeb, 0x1c, 0xf5, 0x2e, 0xa1, 0x37, 0xe3,
	0x7a, 0x9a, 0xf1, 0xe3, 0xed, 0x7c, 0xc2, 0xf8, 0x5b, 0xca, 0x95, 0xc6, 0x36, 0x58, 0x22, 0xa4,
	0xa4, 0x4f, 0x06, 0x0e, 0xb3, 0x44, 0xe8, 0xa5, 0xd0, 0x79, 0x92, 0x2a, 0xe7, 0x0a, 0xe6, 0x1e,
	0x9c, 0xb2, 0x9b, 0x41, 0xff, 0x8d, 0x5c, 0x3f, 0xd7, 0xf3, 0x0b, 0x3d, 0xff, 0xb9, 0x20, 0x58,
	0x05, 0xe3, 0x35, 0x34, 0x8c, 0x43, 0x6a, 0x99, 0xaa, 0xae, 0x5f, 0xfa, 0x37, 0x02, 0x69, 0xcc,
	0xf2, 0xbc, 0x37, 0x83, 0xee, 0x9e, 0xac, 0x5a, 0xcb, 0x44, 0x71, 0xa4, 0xd0, 0x54, 0xe9, 0x72,
	0xc9, 0x95, 0x32, 0xaa, 0x36, 0x2b, 0xc2, 0x2c, 0x63, 0xea, 0xe6, 0x13, 0xd3, 0xd9, 0x66, 0x45,
	0xe8, 0x5d, 0x81, 0xfd, 0x28, 0x97, 0x81, 0x16, 0x32, 0xc1, 0x16, 0x90, 0x8d, 0xa9, 0xb4, 0x18,
	0xd9, 0x64, 0xd1, 0xd6, 0xd0, 0x16, 0x23, 0x5b, 0xef, 0x8b, 0x40, 0x73, 0xe7, 0x01, 0x7d, 0xb0,
	0x57, 0xbb, 0x1a, 0xda, 0x31, 0x46, 0xb1, 0x32, 0x5a, 0x74, 0x63, 0x25, 0x83, 0xb7, 0xd0, 0x58,
	0xf0, 0x48, 0x24, 0xb4, 0x7b, 0xf4, 0x2d, 0x72, 0x10, 0x6f, 0xa0, 0xce, 0x93, 0x90, 0xe2, 0x51,
	0x3e, 0xc3, 0xd0, 0x05, 0xfb, 0x95, 0x07, 0xe1, 0x4a, 0x24, 0x9c, 0xf6, 0xcc, 0x66, 0xca, 0x18,
	0xcf, 0xc0, 0x89, 0x79, 0x28, 0x82, 0x49, 0xa0, 0x03, 0xfa, 0xbf, 0x4f, 0x06, 0x2d, 0x56, 0x5d,
	0x20, 0xc2, 0x1f, 0x1d, 0x44, 0x8a, 0x9e, 0xf4, 0xeb, 0x03, 0x87, 0x99, 0xf3, 0xe8, 0x93, 0x80,
	0x3d, 0xdd, 0x4d, 0x83, 0x0f, 0xe0, 0x94, 0xef, 0x8c, 0x6e, 0x35, 0xe5, 0xcf, 0x9d, 0xbb, 0xa7,
	0x07, 0x73, 0xf9, 0x62, 0xbc, 0x1a, 0x8e, 0xa1, 0xb5, 0xff, 0x9b, 0xf0, 0xbc, 0xc2, 0x0f, 0xfc,
	0x32, 0xf7, 0xf7, 0xe2, 0xbd, 0xda, 0xe2, 0xaf, 0x99, 0xff, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x13, 0xad, 0x5d, 0xd5, 0x02, 0x00, 0x00,
}
