language: go

go:
  - 1.7

#node_js:
#  - #language version
#
#services:
#  - #any supported service
#
#env:

#matrix:

build:
#  pre_ci:
#
#  pre_ci_boot:
#    image_name:
#    image_tag:
#    pull:
#    options:

  ci:
    - export PATH=$PATH:$GOPATH/bin
    - go get -u -v google.golang.org/grpc
    - go get -u -v github.com/golang/protobuf/{proto,protoc-gen-go}
    - ls -al $GOPATH/bin
    - go generate
    - go get -t -v ./...
    - go test -v ./...

#  post_ci:
#    - #command1
#    - #command2
#
#  on_success:
#    - #command1
#    - #command2
#
#  on_failure:
#    - #command1
#    - #command2
#
#  cache:
#  cache_dir_list:
#    - #dir1
#  push:
#
#integrations:
# notifications:
#   - integrationName:
#     type:
#     recipients:
#       - #recp1
#       - #recp2
#
#  hub:
#    - integrationName:
#      type:
#      agent_only: